FROM ucsdets/scipy-ml-notebook:2023.1-stable

RUN pip install --upgrade pip \
    && pip install \
        ipython[all] \
        pandas \
        torch \
        pyg \
        pyTigerGraph \
        numpy \
        scikit-learn \
        matplotlib \
        enum34==1.1.8 \
        xgboost \
        networkx \
