FROM jupyter/base-notebook:python-3.8 

RUN pip install --upgrade pip \
    && pip install \
        ipython[all] \
        networkx \
        pandas \
        stellargraph \
        scikit-learn \
        matplotlib \
        enum34==1.1.8\
        chardet \
        node2vec
